name: E2E (Playwright)

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: E2E smoke (@hedgr/frontend)
    # Fork-safe: only run for PRs from this repo
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm (use version from packageManager)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node (w/ pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install deps
        run: pnpm -r install --frozen-lockfile

      # ---- Performance caches ----
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('apps/frontend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # ---- Fast-fail guard before heavy Next build ----
      - name: Verify @hedgr/ui is resolvable from frontend
        run: pnpm --filter @hedgr/frontend exec node -e "require.resolve('@hedgr/ui'); console.log('ui-ok')"

      - name: Build UI package (if present)
        run: pnpm --filter @hedgr/ui --if-present run build

      - name: Build frontend (smoke)
        run: pnpm --filter @hedgr/frontend run build

      - name: Install Playwright browsers
        run: pnpm --filter @hedgr/frontend exec playwright install --with-deps

      - name: Run Playwright (line reporter)
        run: pnpm --filter @hedgr/frontend run e2e:ci

      - name: Upload Playwright artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            apps/frontend/playwright-report
            apps/frontend/test-results
            apps/frontend/test-results/**/*.zip
          if-no-files-found: ignore
          retention-days: 7
