name: validate
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack + pin pnpm
        run: |
          corepack enable
          corepack install
          node -v
          pnpm -v

      - name: Guard: lockfile/manifest drift
        run: node scripts/ci/guard-lock-drift.mjs

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install (frozen lockfile)
        run: pnpm -r install --frozen-lockfile

      - name: Workspace typecheck
        run: pnpm -w typecheck

      - name: Workspace lint
        run: pnpm -w lint

      - name: Unit tests
        run: pnpm -w test