name: validate
on:
  pull_request:
    branches: [ "*" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_AUTH_MODE: mock
      NEXT_PUBLIC_DEFI_MODE: mock
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install pnpm
        run: corepack install
      - name: Install dependencies
        run: pnpm -r install --frozen-lockfile
      - name: Run checks
        run: pnpm -w typecheck && pnpm -w lint && pnpm -w test
