name: validate

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/renovate.json'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - '.github/renovate.json'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Reusable step block via YAML anchors keeps jobs in sync
x-steps: &setup-steps
  - name: Checkout
    uses: actions/checkout@v4

  - name: Setup pnpm
    uses: pnpm/action-setup@v4
    with:
      run_install: false

  - name: Setup Node (w/ pnpm cache)
    uses: actions/setup-node@v4
    with:
      node-version: '20'
      cache: 'pnpm'
      cache-dependency-path: 'pnpm-lock.yaml'

  - name: Install deps (frozen)
    run: pnpm -r install --frozen-lockfile

  - name: Guard against 'latest' or wildcard versions
    run: node scripts/ci/guard-no-latest.mjs

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - <<: *setup-steps
      - name: Run unit tests
        run: pnpm -w test

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - <<: *setup-steps
      - name: Run typecheck
        run: pnpm -w typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - <<: *setup-steps
      - name: Run lint
        run: pnpm -w lint

  # Optional smoke build to catch missing deps early
  smoke-build:
    name: Build frontend (smoke)
    runs-on: ubuntu-latest
    needs: [unit-tests, typecheck, lint]
    if: ${{ always() }} # keep non-blocking; reports its own status
    timeout-minutes: 15
    steps:
      - <<: *setup-steps
      - name: Build frontend
        run: pnpm --filter @hedgr/frontend run build