name: Validate (unit, types, lint)

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node (w/ pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install deps (frozen)
        run: pnpm -r install --frozen-lockfile

      # Fast guards
      - name: Guard against 'latest' or wildcard versions
        run: node scripts/ci/guard-no-latest.mjs

      - name: Unit tests
        run: pnpm -w test

      - name: Typecheck
        run: pnpm -w typecheck

      - name: Lint
        run: pnpm -w lint

      # Optional smoke build to catch missing deps early
      - name: Build frontend (smoke)
        run: pnpm --filter @hedgr/frontend run build
